name: sum-of-multiples
version: 1.2.0.5

dependencies:
  - base
  - containers

library:
  exposed-modules: SumOfMultiples
  source-dirs: src

benchmarks:
  bench:
    main: Bench.hs
    source-dirs: benchmarks
    dependencies:
      - sum-of-multiples
      - criterion

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - sum-of-multiples
      - hspec
